### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by fclubb** [LSDtopotools/lsdtopytools#1]
Found a couple of small issues with the install instructions, detailed here. 

- Slight typo in the code to create a conda environment
                `conda create -n lsdtopytools python=3.7`

- I didn't quite understand how to find the latest version of lsdtt-xtensor-python as stated in the below line, although 0.0.3 seemed to work:
> where YYY is the latest version of lsdtt-xtensor-python, e.g. 0.0.3

**Comment by fclubb** [comment]
Although I just realised that the second point there is just pointing to the whl files in the directory. This could probably be explained a bit more clearly for idiots like me

**Comment by bgailleton** [comment]
Just saw your issue, I'll update that ASAP
